/**
 * Masked order summaries for local ops lookup (no raw PII).
 */

const maskEmail = (email) => {
  const value = String(email || '').trim();
  if (!value) return '';
  const at = value.indexOf('@');
  if (at <= 0 || at === value.length - 1) return '***';
  const local = value.slice(0, at);
  const domain = value.slice(at + 1);
  const localMask =
    local.length === 1 ? '*' : `${local[0]}***`;
  const parts = domain.split('.');
  const name = parts[0] || '';
  const tld = parts.slice(1).join('.');
  const domainMask =
    name.length <= 1 ? '*' : `${name[0]}***${tld ? `.${tld}` : ''}`;
  return `${localMask}@${domainMask}`;
};

const maskName = (name) => {
  const value = String(name || '').trim();
  if (!value) return '';
  return value
    .split(/\s+/)
    .map((part) => {
      if (!part) return '';
      if (part.length === 1) return '*';
      return `${part[0]}${'*'.repeat(part.length - 1)}`;
    })
    .join(' ');
};

/** Build a PII-safe summary keyed for ops/orders.json. */
const toOrderSummary = (order, { recordedAt = new Date().toISOString() } = {}) => {
  const amountPaise = Number(order?.amount || 0);
  const amountInr = Number.isFinite(amountPaise) ? amountPaise / 100 : 0;
  return {
    appOrderId: String(order?.appOrderId || ''),
    status: String(order?.status || ''),
    productType: String(order?.productType || 'paperback'),
    amountInr,
    amountPaise,
    currency: String(order?.currency || 'INR'),
    customerNameMasked: maskName(order?.name),
    emailMasked: maskEmail(order?.email),
    razorpayOrderId: order?.razorpayOrderId
      ? String(order.razorpayOrderId)
      : null,
    paymentId: order?.paymentId ? String(order.paymentId) : null,
    paymentProvider: order?.paymentProvider
      ? String(order.paymentProvider)
      : null,
    paymentEnvironment: order?.paymentEnvironment
      ? String(order.paymentEnvironment)
      : null,
    createdAt: order?.createdAt ? String(order.createdAt) : null,
    updatedAt: order?.updatedAt ? String(order.updatedAt) : null,
    metaPurchaseSentAt: order?.metaPurchaseSentAt
      ? String(order.metaPurchaseSentAt)
      : null,
    zohoInvoiceNumber: order?.zohoInvoiceNumber
      ? String(order.zohoInvoiceNumber)
      : null,
    zohoInvoiceId: order?.zohoInvoiceId ? String(order.zohoInvoiceId) : null,
    voucherCode: order?.voucherCode ? String(order.voucherCode) : null,
    checkoutBypass: order?.checkoutBypass === true,
    recordedAt,
  };
};

const summariesByOrderId = (orders, options) => {
  const recordedAt = options?.recordedAt || new Date().toISOString();
  const table = {};
  for (const order of orders || []) {
    const id = String(order?.appOrderId || '').trim();
    if (!id) continue;
    table[id] = toOrderSummary(order, { recordedAt });
  }
  return table;
};

const markdownTable = (table) => {
  const cols = [
    'appOrderId',
    'status',
    'productType',
    'amountInr',
    'emailMasked',
    'customerNameMasked',
    'paymentId',
    'razorpayOrderId',
    'zohoInvoiceNumber',
    'createdAt',
    'metaPurchaseSentAt',
  ];
  const rows = Object.keys(table || {})
    .sort()
    .map((id) => table[id]);
  const header = `| ${cols.join(' | ')} |`;
  const sep = `| ${cols.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => {
    return `| ${cols.map((c) => String(row?.[c] ?? '')).join(' | ')} |`;
  });
  return [
    '# Order summaries (PII masked)',
    '',
    'Generated by `backend/npm run export:orders`. Do not store raw email/name here.',
    '',
    header,
    sep,
    ...body,
    '',
  ].join('\n');
};

module.exports = {
  maskEmail,
  maskName,
  toOrderSummary,
  summariesByOrderId,
  markdownTable,
};
